services:
  # Web Service (FastAPI + Telegram Bot)
  - type: web
    name: filin-bot
    env: python
    region: frankfurt
    plan: free
    rootDir: .
    
    # Установка зависимостей
    buildCommand: pip install -r requirements.txt
    
    # Запуск приложения (uvicorn + aiogram webhook)
    startCommand: uvicorn app.webapp.app:app --host 0.0.0.0 --port $PORT
    
    # Переменные окружения
    envVars:
      # Telegram Bot
      - key: BOT_TOKEN
        sync: false
        required: true
      
      # Database (PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: filin-db
          property: connectionString
        required: true
      
      # Web App URL (автоматически подставляется Render)
      - key: WEBAPP_URL
        generateValue: https://${SERVICE_NAME}.onrender.com/webapp
        required: true
      
      # Admin IDs
      - key: ADMIN_IDS
        sync: false
        required: true
      
      # Workers Chat ID (опционально)
      - key: WORKERS_CHAT_ID
        sync: false
        required: false
      
      # Logging
      - key: LOG_PATH
        value: logs.txt
      
      # Default Settings
      - key: DEFAULT_SCHEDULE
        value: "Ежедневно с 14:00 до 2:00"
      
      - key: DEFAULT_CONTACTS
        value: "Phone: +7 (000) 000-00-00\\nAddress: Example street, 1"
      
      # PostgreSQL Pool (оптимизация для Render free tier)
      - key: DB_POOL_SIZE
        value: "5"
      
      - key: DB_MAX_OVERFLOW
        value: "2"
      
      - key: DB_POOL_TIMEOUT
        value: "30"
      
      - key: DB_POOL_RECYCLE
        value: "1800"
    
    # Health check
    healthCheckPath: /health
    healthCheckTimeout: 300
    
    # Auto-deploy при push в main ветку
    autoDeploy: true
    
    # Docker (опционально, можно использовать вместо Python)
    # dockerfilePath: ./Dockerfile

# PostgreSQL Database
databases:
  - name: filin-db
    databaseName: filin
    plan: free
    region: frankfurt
    ipAllowList: []  # Разрешить все IP (Render автоматически настроит)
